<!-- QUI IL CONTENUTO DELLA API -->
<?php

$data = [
    "success" => true,
    "response" => [
         ["poster" => "https://www.onstageweb.com/wp-content/uploads/2018/09/bon-jovi-new-jersey.jpg",
           "title" => "new jersey",
           "author" => "bon jovi",
           "genre" => "Rock",
           "year" => "1988",
         ],
         ["poster" => "https://www.onstageweb.com/wp-content/uploads/2018/09/bon-jovi-new-jersey.jpg",
           "title" => "new jersey",
           "author" => "bon jovi",
           "genre" => "Rock",
           "year" => "1988",
         ],
         ["poster" => "https://www.onstageweb.com/wp-content/uploads/2018/09/bon-jovi-new-jersey.jpg",
           "title" => "new jersey",
           "author" => "bon jovi",
           "genre" => "Rock",
           "year" => "1988",
         ],
         ["poster" => "https://www.onstageweb.com/wp-content/uploads/2018/09/bon-jovi-new-jersey.jpg",
           "title" => "new jersey",
           "author" => "bon jovi",
           "genre" => "Rock",
           "year" => "1988",
         ],
         ["poster" => "https://www.onstageweb.com/wp-content/uploads/2018/09/bon-jovi-new-jersey.jpg",
           "title" => "new jersey",
           "author" => "bon jovi",
           "genre" => "Rock",
           "year" => "1988",
         ],
         ["poster" => "https://www.onstageweb.com/wp-content/uploads/2018/09/bon-jovi-new-jersey.jpg",
           "title" => "new jersey",
           "author" => "bon jovi",
           "genre" => "Rock",
           "year" => "1988",
         ],
         ["poster" => "https://www.onstageweb.com/wp-content/uploads/2018/09/bon-jovi-new-jersey.jpg",
           "title" => "new jersey",
           "author" => "bon jovi",
           "genre" => "Rock",
           "year" => "1988",
         ],
         ["poster" => "https://www.onstageweb.com/wp-content/uploads/2018/09/bon-jovi-new-jersey.jpg",
           "title" => "new jersey",
           "author" => "bon jovi",
           "genre" => "Rock",
           "year" => "1988",
         ],
         ["poster" => "https://www.onstageweb.com/wp-content/uploads/2018/09/bon-jovi-new-jersey.jpg",
           "title" => "new jersey",
           "author" => "bon jovi",
           "genre" => "Rock",
           "year" => "1988",
         ],
         ["poster" => "https://www.onstageweb.com/wp-content/uploads/2018/09/bon-jovi-new-jersey.jpg",
           "title" => "new jersey",
           "author" => "bon jovi",
           "genre" => "Rock",
           "year" => "1988",
         ],



    ]

]